sudo: false

language: node_js
node_js:
  - "8"

cache: yarn

stages:
  - precache
  - test
  - build

jobs:
  include:
    # Install Dependencies
    - stage: precache
      script: true

    # Run tests
    - stage: test
      script: yarn lint

    # Build application
    - stage: build
      script: yarn build
    
    # TODO: Deploy?