sudo: false

language: node_js
node_js:
  - "8"

cache: yarn

jobs:
  include:
    # Install Dependencies
    - stage: precache
      script: true

    # Run tests
    - stage: test
      script: yarn lint

    # Deploy application
    - stage: deploy
      script: yarn build
      deploy:
        provider: pages
        skip_cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local_dir: "dist/"
        target_branch: gh-pages
        on:
          branch: master