language: node_js
node_js:
  - 8

before_script:
  - npm install
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: "dist/"
  target_branch: gh-pages
  on:
    branch: master